version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 066793775137.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t star-wars .
      - docker tag star-wars:latest 066793775137.dkr.ecr.us-east-2.amazonaws.com/star-wars:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 066793775137.dkr.ecr.us-east-2.amazonaws.com/star-wars:latest