# Generated by Django 4.2.6 on 2023-10-11 21:04

from django.db import migrations, models
import starWars.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, storage=starWars.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
